/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package figuras;

import java.awt.Graphics;

/**
 *
 * @author paveg
 */
public class PnlLienzo extends javax.swing.JPanel {
    private Circulo[] circulos;
    /**
     * Creates new form PnlLienzo
     */
    public PnlLienzo(Circulo[] circulos) {
        initComponents();
        this.circulos=circulos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(227, 234, 239));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void paint(Graphics g){
        for (int i = 0; i < circulos.length; i++) {
            if(circulos[i]!=null){
                
                g.setColor(circulos[i].getColor());
                g.fillOval(circulos[i].centro.getX()-circulos[i].getRadio(),
                        circulos[i].centro.getY()-circulos[i].getRadio(),
                        2*circulos[i].getRadio(),2*circulos[i].getRadio());
            }
        }
        
    }
//    public static void main(String[] args) {
//        new PnlLienzo().setVisible(true);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
